apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-server
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: a1008u/webserver_grpc_go_webserver_server:latest
          ports:
            - name: s-s-service
              containerPort: 50052

---
apiVersion: v1
kind: Service
metadata:
  name: s-s-service
spec:
  selector:
    app: server
  ports:
    - port: 50052
      targetPort: s-s-service
