apiVersion: apps/v1
kind: Deployment
metadata:
  # Deployment名
  name: sample-server
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      # podに対するセキュリティ対策
      securityContext:
        runAsUser: 1000
        runAsNonRoot: false
      containers:
        - name: server
          image: a1008u/webserver_grpc_go_webserver_server:v1.0.3
          # コンテナに対するセキュリティ対策
          securityContext:
            readOnlyRootFilesystem: true
          ports:
            - name: s-s-service
              containerPort: 50052

---
apiVersion: v1
kind: Service
metadata:
  # Service名
  name: s-s-service
spec:
  selector:
    # 一致するラベルのリクエストをpodにルーティングする名前
    app: server
  ports:
    - port: 50052
      # 対象のDeploymentのspec.templates.spec.containers.ports.nameと紐づける
      targetPort: s-s-service
