version: '3' # composeファイルのバーション指定
services:
  grpc_go_webserver_client:
    restart: always
    build:
      context: ../..
      dockerfile: helloworld/greeter_client/Dockerfile_client
    ports:
      - "50051:50051"
      - "50054:50054"
      - "9094:9094"
      - "6832:6831"
    depends_on:
      - grpc_go_webserver_server
    environment:
      - SERVER_HOST=grpc_go_webserver_server:50052

  grpc_go_webserver_server:
    restart: always
    build:
      context: ../..
      dockerfile: helloworld/greeter_server/Dockerfile_server
    ports:
      - "9092:9092"
      - "50052:50052"
      - "6831:6831"
