# Dockerfile for gRPC Go_client
# first stage
FROM golang:1.14 as builder

ENV PKG_PATH /go/src/github.com/a1008u/go-grpc
WORKDIR $PKG_PATH
ENV GO111MODULE on

COPY . $PKG_PATH
RUN go mod download

COPY helloworld/greeter_client .
RUN CGO_ENABLED=0 GOOS=linux go build -o greeter_client/app


# second stage
FROM scratch
COPY --from=builder /go/src/github.com/a1008u/go-grpc/greeter_client/app greeter_client/app

# busybox経由でshなどを実行できるようにする
COPY --from=busybox:1.31.1 /bin/busybox /bin/busybox

CMD ["greeter_client/app"]
