version: '3' # composeファイルのバーション指定
services:
  grpc_go:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    tty: true # コンテナの起動永続化
    volumes:
      - ..:/go/src/work # マウントディレクトリ指定
