apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-server2
  namespace: {{.Values.namespace.name}}
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 2
  template:
    metadata:
      labels:
        app: server
    spec:
      # podに対するセキュリティ対策
      securityContext:
        runAsUser: 1000
        runAsNonRoot: false
      containers:
        - name: server
          image: a1008u/webserver_grpc_go_webserver_server:v1.0.4
          # コンテナに対するセキュリティ対策
          securityContext:
            readOnlyRootFilesystem: true
          ports:
            - name: {{ .Values.server.name }}
              containerPort: {{.Values.server.serverport}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.name }}
  namespace: {{.Values.namespace.name}}
spec:
  selector:
    app: server
  ports:
    - port: {{.Values.server.serverport}}
      targetPort: {{ .Values.server.name }}
