apiVersion: apps/v1
kind: Deployment
metadata:
  name:  sample-client2
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      # podに対するセキュリティ対策
      securityContext:
        runAsUser: 1000
        runAsNonRoot: false
      containers:
        - name: client
          image: a1008u/webserver_grpc_go_webserver_client:v1.0.2
          # コンテナに対するセキュリティ対策
          securityContext:
            readOnlyRootFilesystem: true
          ports:
            - name: {{ .Values.client.name }}
              containerPort: 50051
          env:
            - name: SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: server-host2
                  key: target.grpc.server
{{/*            - name: SERVER_HOST*/}}
{{/*              value: s-s-service:50052*/}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.client.name }}
spec:
  selector:
    app: client
  ports:
    - name: http
      port: 50051
      nodePort: 30060
  type: NodePort
